import { MainNavItem, TourNavItem, TourStudyItem } from "@/types/nav"

interface DocsConfig {
  mainNav: MainNavItem[]
  tourNav: TourNavItem[]
  tourStudy: TourStudyItem[]
}

export const docsConfig: DocsConfig = {
  mainNav: [
    { href: "/", title: "หน้าแรก" },
    { href: "/tours/studies", title: "แพ็คเกจเรียน" },
    { href: "/blog", title: "บล็อก" },
    { href: "/about", title: "เกี่ยวกับเรา" },
    { href: "/contact", title: "ติดต่อเรา" },
  ],
  tourNav: [
    {
      items: [
        {
          href: "/tours/studies?duration=short",
          items: [],
          title: "แพ็คเกจเรียนระยะสั้น",
        },
        {
          href: "/tours/studies?duration=long",
          items: [],
          title: "แพ็คเกจเรียนระยะยาว",
        },
      ],
      title: "แพ็คเกจเรียน",
    },
  ],
  tourStudy: [
    {
      items: [
        {
          href: "/tours/studies/1",
          image: "/images/tours/ADWINTER2024.png",
          items: [],
          location: "Harbin, China",
          locationTH: "ฮาร์บิน, ประเทศจีน",
          season: "WINTER",
          seasonTH: "ฤดูหนาว",
          title: "เรียนจีน เที่ยวหิมะเมืองหนาว",
          university: "Harbin Institute of Technology",
          universityTH: "มหาวิทยาลัยเทคโนโลยีฮาร์บิน",
        },
        {
          href: "/tours/studies/2",
          image: "/images/tours/ADOCTOBERCAMP.png",
          items: [],
          location: "Harbin, China",
          locationTH: "ฮาร์บิน, ประเทศจีน",
          season: "SPRING",
          seasonTH: "ฤดูใบไม้ผลิ",
          title: "เรียนจีน เที่ยวจีน",
          university: "Harbin Institute of Technology",
          universityTH: "มหาวิทยาลัยเทคโนโลยีฮาร์บิน",
        },
        {
          href: "/tours/studies/3",
          image: "/images/tours/ADSTUDYMAR2W.png",
          items: [],
          location: "Harbin, China",
          locationTH: "ฮาร์บิน, ประเทศจีน",
          season: "SPRING",
          seasonTH: "ฤดูใบไม้ผลิ",
          title: "เรียนจีน",
          university: "Harbin Institute of Technology",
          universityTH: "มหาวิทยาลัยเทคโนโลยีฮาร์บิน",
        },
        {
          href: "/tours/studies/4",
          image: "/images/tours/ADSTUDYMAR3W.png",
          items: [],
          location: "Harbin, China",
          locationTH: "ฮาร์บิน, ประเทศจีน",
          season: "SPRING",
          seasonTH: "ฤดูใบไม้ผลิ",
          title: "เรียนจีน",
          university: "Harbin Institute of Technology",
          universityTH: "มหาวิทยาลัยเทคโนโลยีฮาร์บิน",
        },
        {
          href: "/tours/studies/5",
          image: "/images/tours/ADSTUDYMAR1M.png",
          items: [],
          location: "Harbin, China",
          locationTH: "ฮาร์บิน, ประเทศจีน",
          season: "SPRING",
          seasonTH: "ฤดูใบไม้ผลิ",
          title: "เรียนจีน",
          university: "Harbin Institute of Technology",
          universityTH: "มหาวิทยาลัยเทคโนโลยีฮาร์บิน",
        },
        {
          href: "/tours/studies/6",
          image: "/images/tours/ADSTUDYMAR2M.png",
          items: [],
          location: "Harbin, China",
          locationTH: "ฮาร์บิน, ประเทศจีน",
          season: "SPRING",
          seasonTH: "ฤดูใบไม้ผลิ",
          title: "เรียนจีน",
          university: "Harbin Institute of Technology",
          universityTH: "มหาวิทยาลัยเทคโนโลยีฮาร์บิน",
        },
        {
          href: "/tours/studies/7",
          image: "/images/tours/ADSTUDYMAR3M.png",
          items: [],
          location: "Harbin, China",
          locationTH: "ฮาร์บิน, ประเทศจีน",
          season: "SPRING",
          seasonTH: "ฤดูใบไม้ผลิ",
          title: "เรียนจีน",
          university: "Harbin Institute of Technology",
          universityTH: "มหาวิทยาลัยเทคโนโลยีฮาร์บิน",
        },
        {
          href: "/tours/studies/8",
          image: "/images/tours/ADJULYCAMPSTUDY_HIT.png",
          items: [],
          location: "Harbin, China",
          locationTH: "ฮาร์บิน, ประเทศจีน",
          season: "SPRING",
          seasonTH: "ฤดูใบไม้ผลิ",
          title: "เรียนจีน",
          university: "Harbin Institute of Technology",
          universityTH: "มหาวิทยาลัยเทคโนโลยีฮาร์บิน",
        },
        {
          href: "/tours/studies/9",
          image: "/images/tours/ADWINTER2025.png",
          items: [],
          location: "Harbin, China",
          locationTH: "ฮาร์บิน, ประเทศจีน",
          season: "SPRING",
          seasonTH: "ฤดูใบไม้ผลิ",
          title: "เรียนจีน",
          university: "Harbin Institute of Technology",
          universityTH: "มหาวิทยาลัยเทคโนโลยีฮาร์บิน",
        },
        {
          href: "/tours/studies/10",
          image: "/images/tours/ADSTUDYMAR2W2025.png",
          items: [],
          location: "Harbin, China",
          locationTH: "ฮาร์บิน, ประเทศจีน",
          season: "SPRING",
          seasonTH: "ฤดูใบไม้ผลิ",
          title: "เรียนจีน",
          university: "Harbin Normal University",
          universityTH: "มหาวิทยาลัยครูฮาร์บิน",
        },
        {
          href: "/tours/studies/11",
          image: "/images/tours/ADSTUDYMAR3W2025.png",
          items: [],
          location: "Harbin, China",
          locationTH: "ฮาร์บิน, ประเทศจีน",
          season: "SPRING",
          seasonTH: "ฤดูใบไม้ผลิ",
          title: "เรียนจีน",
          university: "Harbin Normal University",
          universityTH: "มหาวิทยาลัยครูฮาร์บิน",
        },
        {
          href: "/tours/studies/12",
          image: "/images/tours/ADSTUDYMAR1M2025.png",
          items: [],
          location: "Harbin, China",
          locationTH: "ฮาร์บิน, ประเทศจีน",
          season: "SPRING",
          seasonTH: "ฤดูใบไม้ผลิ",
          title: "เรียนจีน",
          university: "Harbin Normal University",
          universityTH: "มหาวิทยาลัยครูฮาร์บิน",
        },
        {
          href: "/tours/studies/13",
          image: "/images/tours/ADSTUDYMAR2M2025.png",
          items: [],
          location: "Harbin, China",
          locationTH: "ฮาร์บิน, ประเทศจีน",
          season: "SPRING",
          seasonTH: "ฤดูใบไม้ผลิ",
          title: "เรียนจีน",
          university: "Harbin Normal University",
          universityTH: "มหาวิทยาลัยครูฮาร์บิน",
        },
        {
          href: "/tours/studies/14",
          image: "/images/tours/ADSTUDYMAR3M2025.png",
          items: [],
          location: "Harbin, China",
          locationTH: "ฮาร์บิน, ประเทศจีน",
          season: "SPRING",
          seasonTH: "ฤดูใบไม้ผลิ",
          title: "เรียนจีน",
          university: "Harbin Normal University",
          universityTH: "มหาวิทยาลัยครูฮาร์บิน",
        },
      ],
      title: "แพ็คเกจเรียนระยะสั้น",
    },
    {
      items: [
        {
          href: "/tours/studies/15",
          image: "/images/tours/ADSTUDY1YNORMAL.png",
          items: [],
          location: "Harbin, China",
          locationTH: "ฮาร์บิน, ประเทศจีน",
          season: "SPRING",
          seasonTH: "ฤดูใบไม้ผลิ",
          title: "เรียนจีนระยะยาว",
          university: "Harbin Normal University",
          universityTH: "มหาวิทยาลัยครูฮาร์บิน",
        },
        {
          href: "/tours/studies/16",
          image: "/images/tours/ADSTUDY1YHIT.png",
          items: [],
          location: "Harbin, China",
          locationTH: "ฮาร์บิน, ประเทศจีน",
          season: "SPRING",
          seasonTH: "ฤดูใบไม้ผลิ",
          title: "เรียนจีนระยะยาว",
          university: "Harbin Institute of Technology",
          universityTH: "มหาวิทยาลัยเทคโนโลยีฮาร์บิน",
        },
        {
          href: "/tours/studies/17",
          image: "/images/tours/ADSTUDY1TNORMAL.png",
          items: [],
          location: "Harbin, China",
          locationTH: "ฮาร์บิน, ประเทศจีน",
          season: "SPRING",
          seasonTH: "ฤดูใบไม้ผลิ",
          title: "เรียนภาษาจีน",
          university: "Harbin Normal University",
          universityTH: "มหาวิทยาลัยครูฮาร์บิน",
        },
        {
          href: "/tours/studies/18",
          image: "/images/tours/ADLONGTERMSTUDY1T_HIT.png",
          items: [],
          location: "Harbin, China",
          locationTH: "ฮาร์บิน, ประเทศจีน",
          season: "SPRING",
          seasonTH: "ฤดูใบไม้ผลิ",
          title: "เรียนภาษาจีน",
          university: "Harbin Institute of Technology",
          universityTH: "มหาวิทยาลัยเทคโนโลยีฮาร์บิน",
        },
        {
          href: "/tours/studies/19",
          image: "/images/tours/ADSTUDYHARBIN_SUMMER21DAYS.png",
          items: [],
          location: "Harbin, China",
          locationTH: "ฮาร์บิน, ประเทศจีน",
          season: "SPRING",
          seasonTH: "ฤดูใบไม้ผลิ",
          title: "เรียนจีน เที่ยวจีน พร้อมศึกษาวัฒนธรรมจีน",
          university: "Harbin Institute of Technology",
          universityTH: "มหาวิทยาลัยเทคโนโลยีฮาร์บิน",
        },
      ],
      title: "แพ็คเกจเรียนระยะยาว",
    },
  ],
}
