export const siteConfig = {
  name: "บริษัท แอดเวนเท็กซ์ อินเตอร์เนชั่นแนล กรุ๊ป จำกัด",
  description: "สถาบันการศึกษาต่อต่างประเทศ",
  ogImage: "https://www.adventex.co.th/og.jpg",
  url: process.env.NEXT_PUBLIC_APP_URL
    ? process.env.NEXT_PUBLIC_APP_URL
    : "http://localhost:3000",
  links: {
    facebook: "https://web.facebook.com/profile.php?id=61552757897555",
    instagram: "https://www.instagram.com/adventexeducation/?hl=en",
    line: "https://line.me/R/ti/p/@094aeddz",
    tiktok: "https://www.tiktok.com/@harbin.pp",
  },
  keywords: [
    "บริษัท แอดเวนเท็กซ์ อินเตอร์เนชั่นแนล กรุ๊ป จำกัด",
    "บริษัท แอดเวนเท็กซ์ อินเตอร์เนชั่นแนล",
    "บริษัท แอดเวนเท็กซ์",
    "แอดเวนเท็กซ์",
    "แอดเวนเท็กซ",
    "แอดเวนเท็ก",
    "แอดเวนเทก",
    "แอดเวนเทค",
    "adventex",
    "adventex education",
    "adventex international",
    "Adventex",
    "Adventex Education",
    "Adventex International",
    "เรียนต่อต่างประเทศ",
    "ศึกษาต่อต่างประเทศ",
    "เรียนต่อจีน",
    "ศึกษาต่อจีน",
    "แพ็คเกจเรียนต่างประเทศ",
    "study abroad",
    "study in China",
    "Chinese language courses",
    "international education",
    "หลักสูตรภาษาจีน",
    "ภาษาที่สาม",
    "third language",
    "ที่ปรึกษาการศึกษาต่างประเทศ",
    "education consultant",
    "ทุนการศึกษาต่างประเทศ",
    "international scholarships",
    "มหาวิทยาลัยในจีน",
    "Chinese universities",
    "Harbin Institute of Technology",
    "HIT",
    "Hunan University",
    "HNU",
    "study tours",
    "ทัวร์การศึกษา",
    "การเตรียมตัวเรียนต่างประเทศ",
    "prepare for study abroad",
    "วีซ่านักเรียน",
    "student visa",
    "หอพักนักศึกษาต่างชาติ",
    "international student accommodation",
  ],
}

export type SiteConfig = typeof siteConfig

export const META_THEME_COLORS = {
  dark: "#09090b",
  light: "#ffffff",
}
